<!DOCTYPE html>
<html>
<head>
<style>
    body { font-family: 'Times New Roman', Times, serif; background-color: #f8fafc; margin: 0; padding: 20px; color: #1e293b; }
    .container { max-width: 700px; margin: 0 auto; background: #ffffff; padding: 40px; border: 10px double #0f172a; }
    .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #0f172a; padding-bottom: 20px; }
    .title { color: #0f172a; font-size: 28px; font-weight: bold; margin-bottom: 10px; letter-spacing: 2px; }
    .subtitle { color: #64748b; font-size: 14px; text-transform: uppercase; letter-spacing: 1px; }
    .content { font-size: 18px; line-height: 1.8; text-align: justify; margin-bottom: 40px; }
    .details-table { width: 100%; margin: 30px 0; border-collapse: collapse; }
    .details-table td { padding: 10px; border-bottom: 1px solid #e2e8f0; font-family: 'Helvetica Neue', Arial, sans-serif; }
    .details-table td:first-child { font-weight: bold; color: #64748b; width: 40%; text-transform: uppercase; font-size: 12px; }
    .details-table td:last-child { color: #0f172a; font-weight: bold; }
    .signatures { margin-top: 50px; display: flex; justify-content: space-between; }
    .signature-line { border-top: 1px solid #0f172a; padding-top: 10px; font-style: italic; width: 250px; text-align: center; }
    .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #64748b; font-family: 'Helvetica Neue', Arial, sans-serif; }
</style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="title">CERTIFICATE OF AUTHORIZATION</div>
            <div class="subtitle">Official Account Approval Record</div>
        </div>
        
        <div class="content">
            This certifies that the account registration for the following individual has been formally reviewed and <strong>APPROVED</strong> by the System Administration for access to the {{ config('app.name') }}.
            
            <table class="details-table">
                <tr>
                    <td>Authorized User</td>
                    <td>{{ $user->full_name }}</td>
                </tr>
                <tr>
                    <td>Organization</td>
                    <td>{{ $user->organization }}</td>
                </tr>
                <tr>
                    <td>Designation</td>
                    <td>{{ $user->designation }}</td>
                </tr>
                <tr>
                    <td>Email Address</td>
                    <td>{{ $user->email }}</td>
                </tr>
                <tr>
                    <td>Date of Approval</td>
                    <td>{{ $user->approved_at ? $user->approved_at->format('F d, Y h:i A') : now()->format('F d, Y h:i A') }}</td>
                </tr>
                <tr>
                    <td>Certificate Reference</td>
                    <td style="font-family: monospace; letter-spacing: 1px;">{{ $user->approval_certificate_token }}</td>
                </tr>
            </table>
            
            <p style="font-size: 14px; text-align: center; font-style: italic;">
                The user is now granted active status and may securely access the system using their verified email address.
            </p>
        </div>
        
        <div style="margin-top: 40px; text-align: right;">
            <div style="display: inline-block; text-align: center;">
                <div style="margin-bottom: 5px; font-family: 'Helvetica Neue', Arial, sans-serif; font-weight: bold;">{{ $user->approvedBy ? $user->approvedBy->full_name : 'System Administrator' }}</div>
                <div style="border-top: 1px solid #0f172a; padding-top: 5px; font-size: 14px; width: 200px;">Approving Authority</div>
            </div>
        </div>
        
        <div class="footer">
            This email serves as an official and permanent record of account authorization.<br>
            Generated by {{ config('app.name') }}
        </div>
    </div>
</body>
</html>
